version: "3.8"

services:
  airflow:
    image: apache/airflow:2.7.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  spark:
    image: bitnami/spark:latest
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - spark

  expectations:
    image: python:3.11
    volumes:
      - ./src:/app
    working_dir: /app/validation
    command: ["python", "run_validations.py"]
